{
  "openapi": "3.0.3",
  "info": {
    "title": "Payroll",
    "version": "0.1.0"
  },
  "tags": [
    {
      "name": "Authentication"
    },
    {
      "name": "User management"
    }
  ],
  "components": {
    "schemas": {
      "LoginRequest": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": [
          "username",
          "password"
        ],
        "example": {
          "username": "testuser",
          "password": "testpass"
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        }
      },
      "BadRequestResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "CreateUserRequest": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string"
          },
          "second_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "second_last_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "payment_period": {
            "type": "integer",
            "enum": [
              1,
              2
            ]
          },
          "business_unit": {
            "type": "integer",
            "enum": [
              1,
              2
            ]
          },
          "salary": {
            "type": "number"
          }
        },
        "required": [
          "first_name",
          "last_name",
          "email",
          "payment_period",
          "business_unit",
          "salary"
        ]
      },
      "UserInformationResponse": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string"
          },
          "second_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "second_last_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "payment_period": {
            "type": "string"
          },
          "business_unit": {
            "type": "string"
          },
          "on_leave": {
            "type": "boolean"
          },
          "active": {
            "type": "boolean"
          },
          "salary": {
            "type": "number"
          }
        }
      },
      "BasicUserInformationResponse": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string"
          },
          "second_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "second_last_name": {
            "type": "string"
          },
          "payment_period": {
            "type": "string"
          },
          "business_unit": {
            "type": "string"
          },
          "on_leave": {
            "type": "boolean"
          },
          "salary": {
            "type": "number"
          }
        }
      },
      "UpdateUserRequest": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "first_name": {
            "type": "string"
          },
          "second_name": {
            "type": "string"
          },
          "last_name": {
            "type": "string"
          },
          "second_last_name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "payment_period": {
            "type": "integer",
            "enum": [
              1,
              2
            ]
          },
          "business_unit": {
            "type": "integer",
            "enum": [
              1,
              2
            ]
          },
          "salary": {
            "type": "number"
          }
        },
        "required": [
          "id"
        ]
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "scheme": "Bearer",
        "type": "http"
      }
    }
  },
  "paths": {
    "/api/login": {
      "post": {
        "summary": "Checks credentials and returns session token",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returns a session token",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Username and/or password are incorrect",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BadRequestResponse"
                },
                "example": {
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/api/users": {
      "get": {
        "summary": "Get a list of users",
        "tags": [
          "User management"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "order",
            "schema": {
              "type": "string",
              "enum": [
                "name",
                "salary"
              ]
            }
          },
          {
            "in": "query",
            "name": "by",
            "schema": {
              "type": "string",
              "enum": [
                "asc",
                "desc"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/BasicUserInformationResponse"
                  }
                },
                "example": [
                  {
                    "first_name": "John",
                    "second_name": null,
                    "last_name": "Doe",
                    "second_last_name": null,
                    "payment_method": "Quincenal",
                    "business_unit": "Michelada",
                    "on_leave": false,
                    "salary": 5000.45
                  },
                  {
                    "first_name": "Jane",
                    "second_name": "Dill",
                    "last_name": "Don",
                    "second_last_name": "S",
                    "payment_method": "Mensual",
                    "business_unit": "Arkus Nexus",
                    "on_leave": false,
                    "salary": 150000
                  }
                ]
              }
            }
          },
          "400": {
            "description": "You sent one or more invalid parameters",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "errors": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "message": "Invalid parameters",
                  "errors": [
                    "order"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/api/user": {
      "get": {
        "tags": [
          "User management"
        ],
        "summary": "Get the information of a specific user",
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Retuns requested user's information",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserInformationResponse"
                },
                "example": {
                  "first_name": "John",
                  "second_name": null,
                  "last_name": "Doe",
                  "second_last_name": null,
                  "email": "jdoe@example.net",
                  "role": "User",
                  "payment_period": "Quincenal",
                  "business_unit": "Michelada",
                  "on_leave": false,
                  "active": false,
                  "salary": 5000.45
                }
              }
            }
          },
          "400": {
            "description": "Missing required parameters"
          },
          "403": {
            "description": "User is missing the \"Read User Information\" privilege"
          },
          "404": {
            "description": "A user with the specified ID does not exist"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "post": {
        "tags": [
          "User management"
        ],
        "summary": "Add a user to the payroll",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserRequest"
              },
              "example": {
                "first_name": "John",
                "last_name": "Doe",
                "email": "jdoe@example.net",
                "payment_period": 1,
                "business_unit": 1,
                "salary": 5000.45
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User was created successfully"
          },
          "400": {
            "description": "Missing required field"
          },
          "403": {
            "description": "User is missing the \"Create User\" privilege"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "User management"
        ],
        "summary": "Edit a user information",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              },
              "example": {
                "id": 1,
                "salary": 10000.85,
                "payment_period": 2
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "User information was edited successfully"
          },
          "400": {
            "description": "Missing required files"
          },
          "403": {
            "description": "User is missing the \"Edit User Information\" privilege"
          },
          "404": {
            "description": "The user you want to edit does not exist"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "User management"
        ],
        "summary": "Mark a user as inactive",
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "User was marked as inactive successfully"
          },
          "400": {
            "description": "Missing required files"
          },
          "403": {
            "description": "User is missing the \"Delete User\" privilege"
          },
          "404": {
            "description": "The user you want to delete does not exist"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  }
}